---
-  hosts: group3
   vars: 
     pkg_name: mysql
   tasks:
   -  name: installing {{pkg_name}}
      yum:
        name: mysql57-server
        state: present
   -  name: restrting {{pkg_name}}
      service:
        name: mysqld
        state: started
   -   name: apply security for {{pkg_name}}
       expect:
         command: mysql_secure_installation
         responses:
           'Press y\|Y for Yes, any other key for No:': 'y'
           'Please enter 0 = LOW, 1 = MEDIUM and 2 = STRONG:': '0'
           'New password:': 'alkahli12121990'
           'Re-enter new password:': 'alkahli12121990'
           'Do you wish to continue with the password provided\?\(Press y\|Y for Yes, any other key for No\) :': 'yes'
           'Remove anonymous users\? \(Press y\|Y for Yes, any other key for No\) :': 'yes'
           'Disallow root login remotely\? \(Press y\|Y for Yes, any other key for No\) :': 'yes'
           'Remove test database and access to it\? \(Press y\|Y for Yes, any other key for No\) :': 'yes'
           'Reload privilege tables now\? \(Press y\|Y for Yes, any other key for No\) :': 'yes'
         echo: yes
  # -   name: apply security for {{pkg_name}}
   #    expect:
    #     command: mysql -u root -p
     #    responses:
      #      Question:
       #    -  Enter password: "1990121"
            
